# Generated by Django 4.1.2 on 2024-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(db_column='idAutor', primary_key=True, serialize=False)),
                ('nom_autor', models.CharField(max_length=50)),
                ('nacionalidad_autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=50)),
                ('desc_categoria', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id_libro', models.AutoField(db_column='idLibro', primary_key=True, serialize=False)),
                ('titulo_libro', models.CharField(max_length=50)),
                ('anio_publicacion', models.CharField(max_length=5)),
                ('desc_libro', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id_nav', models.AutoField(db_column='idNav', primary_key=True, serialize=False)),
                ('nom_nav', models.CharField(max_length=20)),
                ('url_nav', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
